### ISSUE TITLE
Time difference

### ISSUE THREAD

**Issue by M5oul** [duniter/cesium#444] opened 2017-05-02 16:17 UTC
There is one hour of difference between blocks generated and blocks [displayed on Cesium](https://g1.duniter.fr/#/app/network).

**Comment by blavenie** [comment] 2017-05-03 08:41
Timestamp should be displayed as : `timestamp + parameters.median_time_blocks/2 * parameters.avg_gen_time`

**Comment by blavenie** [comment] 2017-06-13 11:10
duplicate of #303

**Closed by blavenie** 2017-06-13 11:10 UTC
Labels: duplicate, enhancement
